---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"
    ignore:
      # we need to fine-control the exact version for VS compat, and we have a distinct version for tests
      - dependency-name: "Microsoft.CodeAnalysis.CSharp.Workspaces"  
    groups:
      roslyn:
        patterns:
          - "Microsoft.CodeAnalysis*"
      vssdk:
        patterns:
          - "Microsoft.VisualStudio*"
          - "Microsoft.VSSDK*" 
      tests:
        patterns:
          - "xunit*" 
